# Generated by Django 5.1.7 on 2026-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_alter_subscriberprofile_google_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevent',
            name='channel_subscriber_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='subscriber_change_since_last_scan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriberprofile',
            name='channel_subscriber_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriberprofile',
            name='subscriber_change_since_last_scan',
            field=models.IntegerField(default=0),
        ),
    ]
