# Generated by Django 5.1.7 on 2026-04-22 00:00

import random
from django.db import migrations, models


SAMPLE_CHANNELS = [
    {
        'name': 'Google Developers',
        'handle': '@GoogleDevelopers',
        'youtube_url': 'https://www.youtube.com/@GoogleDevelopers',
        'description': 'Official Google Developers channel with engineering videos and product updates.',
        'display_order': 1,
    },
    {
        'name': 'YouTube Creators',
        'handle': '@YouTubeCreators',
        'youtube_url': 'https://www.youtube.com/@YouTubeCreators',
        'description': 'Official creator education and growth resources from YouTube.',
        'display_order': 2,
    },
    {
        'name': 'Google',
        'handle': '@google',
        'youtube_url': 'https://www.youtube.com/@google',
        'description': 'Official Google announcements, product launches, and stories.',
        'display_order': 3,
    },
    {
        'name': 'TED',
        'handle': '@TED',
        'youtube_url': 'https://www.youtube.com/@TED',
        'description': 'Talks and ideas from scientists, entrepreneurs, and educators.',
        'display_order': 4,
    },
    {
        'name': 'NASA',
        'handle': '@NASA',
        'youtube_url': 'https://www.youtube.com/@NASA',
        'description': 'Space missions, science explainers, and live launches.',
        'display_order': 5,
    },
    {
        'name': 'freeCodeCamp.org',
        'handle': '@freecodecamp',
        'youtube_url': 'https://www.youtube.com/@freecodecamp',
        'description': 'Long-form coding tutorials and software engineering lessons.',
        'display_order': 6,
    },
    {
        'name': 'Traversy Media',
        'handle': '@TraversyMedia',
        'youtube_url': 'https://www.youtube.com/@TraversyMedia',
        'description': 'Web development tutorials covering frontend and backend tools.',
        'display_order': 7,
    },
    {
        'name': 'Programming with Mosh',
        'handle': '@programmingwithmosh',
        'youtube_url': 'https://www.youtube.com/@programmingwithmosh',
        'description': 'Programming tutorials and career-focused developer content.',
        'display_order': 8,
    },
    {
        'name': 'Fireship',
        'handle': '@Fireship',
        'youtube_url': 'https://www.youtube.com/@Fireship',
        'description': 'Fast-paced software development explainers and updates.',
        'display_order': 9,
    },
    {
        'name': 'Khan Academy',
        'handle': '@khanacademy',
        'youtube_url': 'https://www.youtube.com/@khanacademy',
        'description': 'Educational lessons across math, science, and computing.',
        'display_order': 10,
    },
]


def seed_required_channels(apps, schema_editor):
    RequiredChannel = apps.get_model('subscribers', 'RequiredChannel')
    SubscriberProfile = apps.get_model('subscribers', 'SubscriberProfile')
    RequiredChannelAssignment = apps.get_model('subscribers', 'RequiredChannelAssignment')

    seeded_channels = []
    for payload in SAMPLE_CHANNELS:
        channel, _ = RequiredChannel.objects.get_or_create(
            name=payload['name'],
            defaults=payload,
        )
        seeded_channels.append(channel)

    available_channels = list(
        RequiredChannel.objects.filter(is_active=True).order_by('display_order', 'name')
    )
    for profile in SubscriberProfile.objects.all():
        assigned_count = RequiredChannelAssignment.objects.filter(
            profile=profile,
            channel__is_active=True,
        ).count()
        missing_count = max(2 - assigned_count, 0)
        if missing_count <= 0 or not available_channels:
            continue

        assigned_channel_ids = set(
            RequiredChannelAssignment.objects.filter(profile=profile).values_list('channel_id', flat=True)
        )
        remaining = [channel for channel in available_channels if channel.id not in assigned_channel_ids]
        if not remaining:
            continue

        for channel in random.sample(remaining, min(missing_count, len(remaining))):
            RequiredChannelAssignment.objects.get_or_create(profile=profile, channel=channel)


def unseed_required_channels(apps, schema_editor):
    RequiredChannel = apps.get_model('subscribers', 'RequiredChannel')
    RequiredChannel.objects.filter(name__in=[item['name'] for item in SAMPLE_CHANNELS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_scanevent_channel_subscriber_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(blank=True, max_length=255)),
                ('channel_id', models.CharField(blank=True, max_length=128)),
                ('youtube_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequiredChannelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='assignments', to='subscribers.requiredchannel')),
                ('profile', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='required_channel_assignments', to='subscribers.subscriberprofile')),
            ],
            options={
                'ordering': ['assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='requiredchannelassignment',
            constraint=models.UniqueConstraint(fields=('profile', 'channel'), name='unique_required_channel_assignment'),
        ),
        migrations.RunPython(seed_required_channels, unseed_required_channels),
    ]
