# Generated by Django 5.1.7 on 2026-04-22 00:30

from django.db import migrations, models


CHANNEL_CATEGORY_MAP = {
    'Google Developers': 'technology',
    'YouTube Creators': 'education',
    'Google': 'technology',
    'TED': 'education',
    'NASA': 'education',
    'freeCodeCamp.org': 'education',
    'Traversy Media': 'technology',
    'Programming with Mosh': 'education',
    'Fireship': 'technology',
    'Khan Academy': 'education',
}


def seed_channel_categories(apps, schema_editor):
    RequiredChannel = apps.get_model('subscribers', 'RequiredChannel')
    RequiredChannelAssignment = apps.get_model('subscribers', 'RequiredChannelAssignment')
    SubscriberProfile = apps.get_model('subscribers', 'SubscriberProfile')

    for channel in RequiredChannel.objects.all():
        channel.category = CHANNEL_CATEGORY_MAP.get(channel.name, 'other')
        channel.save(update_fields=['category'])

    for profile in SubscriberProfile.objects.all():
        total = RequiredChannelAssignment.objects.filter(
            profile=profile,
            channel__is_active=True,
        ).count()
        verified = RequiredChannelAssignment.objects.filter(
            profile=profile,
            channel__is_active=True,
            status='verified',
        ).count()
        profile.required_channel_total = total
        profile.required_channel_verified_count = verified
        profile.save(update_fields=['required_channel_total', 'required_channel_verified_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_requiredchannel_requiredchannelassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='required_channel_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriberprofile',
            name='required_channel_verified_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requiredchannel',
            name='category',
            field=models.CharField(
                choices=[
                    ('education', 'Education'),
                    ('entertainment', 'Entertainment'),
                    ('sports', 'Sports'),
                    ('technology', 'Technology'),
                    ('music', 'Music'),
                    ('gaming', 'Gaming'),
                    ('lifestyle', 'Lifestyle'),
                    ('news', 'News'),
                    ('other', 'Other'),
                ],
                db_index=True,
                default='other',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='requiredchannel',
            name='channel_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='requiredchannel',
            name='handle',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='requiredchannelassignment',
            name='last_interaction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requiredchannelassignment',
            name='opened_youtube_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requiredchannelassignment',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requiredchannelassignment',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('viewed', 'Viewed'),
                    ('opened', 'Opened'),
                    ('verified', 'Verified'),
                ],
                db_index=True,
                default='pending',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='requiredchannelassignment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requiredchannelassignment',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='requiredchannelassignment',
            index=models.Index(fields=['profile', 'status'], name='assignment_profile_status_idx'),
        ),
        migrations.AddIndex(
            model_name='requiredchannelassignment',
            index=models.Index(fields=['channel', 'status'], name='assignment_channel_status_idx'),
        ),
        migrations.RunPython(seed_channel_categories, migrations.RunPython.noop),
    ]
