# Generated by Django 5.1.7 on 2026-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0005_assignment_research_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='handle',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
