# Generated by Django 5.1.7 on 2026-04-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0006_subscriberprofile_handle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_handle', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('technology', 'Technology'), ('music', 'Music'), ('gaming', 'Gaming'), ('lifestyle', 'Lifestyle'), ('news', 'News'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channel_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'channel_name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_task_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('channel_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subscribers.channeltask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='channeltask',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_channel_tasks', through='subscribers.ChannelTaskAssignment', through_fields=('channel_task', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='channeltaskassignment',
            index=models.Index(fields=['channel_task', 'user'], name='channel_task_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='channeltaskassignment',
            constraint=models.UniqueConstraint(fields=('channel_task', 'user'), name='unique_channel_task_user_assignment'),
        ),
    ]
