# Generated by Django 5.1.7 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0007_channeltask_channeltaskassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='channel_total_view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriberprofile',
            name='channel_video_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
