# Generated by Django 5.1.7 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0008_subscriberprofile_channel_total_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='subscribed_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
