# Generated by Django 5.1.7 on 2026-04-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0009_subscriberprofile_subscribed_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('subscribed_via_api', models.BooleanField(default=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_channel_records', to='subscribers.requiredchannel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_channels', to='subscribers.subscriberprofile')),
            ],
            options={
                'ordering': ['-last_verified_at', '-subscribed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subscribedchannel',
            constraint=models.UniqueConstraint(fields=('profile', 'channel'), name='unique_profile_subscribed_channel'),
        ),
        migrations.AddIndex(
            model_name='subscribedchannel',
            index=models.Index(fields=['profile', 'is_verified'], name='sub_prof_ver_idx'),
        ),
    ]
