# Generated by Django 5.1.7 on 2026-04-27

from django.db import migrations, models
from django.db.models import F


def backfill_profile_score(apps, schema_editor):
    SubscriberProfile = apps.get_model('subscribers', 'SubscriberProfile')
    SubscriberProfile.objects.update(score=F('required_channel_verified_count'))


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0010_subscribedchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_profile_score, migrations.RunPython.noop),
        migrations.AlterModelTable(
            name='subscriberprofile',
            table='user_profile_table',
        ),
    ]
