# Generated by Django 5.1.7 on 2026-04-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0011_subscriberprofile_score_and_user_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscriberprofile',
            table='profile_table',
        ),
        migrations.CreateModel(
            name='TopUserSubscribeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('subscribed', 'Subscribed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_user_subscribe_tasks', to='subscribers.subscriberprofile')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_user_subscribe_targets', to='subscribers.subscriberprofile')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='topusersubscribetask',
            constraint=models.UniqueConstraint(fields=('profile', 'target_profile'), name='unique_top_user_subscribe_task'),
        ),
        migrations.AddIndex(
            model_name='topusersubscribetask',
            index=models.Index(fields=['profile', 'status'], name='top_usr_prof_status_idx'),
        ),
        migrations.AddIndex(
            model_name='topusersubscribetask',
            index=models.Index(fields=['target_profile', 'status'], name='top_usr_tgt_status_idx'),
        ),
    ]
