# Generated by Django 5.1.7 on 2026-04-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0012_profile_table_and_top_user_subscribe_task"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChannelTaskAssignment",
        ),
        migrations.DeleteModel(
            name="RequiredChannelAssignment",
        ),
        migrations.DeleteModel(
            name="ScanEvent",
        ),
        migrations.DeleteModel(
            name="SubscribedChannel",
        ),
        migrations.DeleteModel(
            name="ChannelTask",
        ),
        migrations.DeleteModel(
            name="RequiredChannel",
        ),
    ]
