# Generated by Django 5.1.7 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0013_remove_channeltaskassignment_channel_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topusersubscribetask",
            name="verified_status",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
