# Generated by Django 5.1.7 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0014_topusersubscribetask_verified_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberprofile",
            name="last_verified_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
