# Generated by Django 5.1.7 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0015_subscriberprofile_last_verified_sync_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="topusersubscribetask",
            name="score_awarded",
            field=models.BooleanField(default=False),
        ),
    ]
