# Generated by Django 5.1.7 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0020_remove_topusersubscribetask_score_awarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberprofile",
            name="reserved_score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
