# Generated by Django 5.1.1 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0022_alter_user_managers_alter_user_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberprofile",
            name="facebook_followers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriberprofile",
            name="facebook_profile_url",
            field=models.URLField(blank=True),
        ),
    ]
