# Generated by Django 5.1.1 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0023_subscriberprofile_facebook_followers_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topusersubscribetask",
            name="facebook_followed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topusersubscribetask",
            name="facebook_followed_status",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
