# Generated by Django 5.1.1 on 2026-05-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0024_topusersubscribetask_facebook_followed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("facebook_subject_id", models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ("facebook_email", models.EmailField(blank=True, max_length=254)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("profile_url", models.URLField(blank=True)),
                ("profile_picture_url", models.URLField(blank=True)),
                ("access_token", models.TextField(blank=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facebook_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "facebook_profile_table",
                "ordering": ["-updated_at"],
            },
        ),
    ]
