# Generated by Django 5.1.1 on 2026-05-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0025_facebookprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookTaskAssing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("followed_status", models.BooleanField(db_index=True, default=False)),
                ("followed_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facebook_task_assignments",
                        to="subscribers.subscriberprofile",
                    ),
                ),
                (
                    "target_facebook_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_facebook_tasks",
                        to="subscribers.facebookprofile",
                    ),
                ),
            ],
            options={
                "db_table": "facebook_task_assing",
                "ordering": ["-updated_at", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "target_facebook_profile"),
                        name="unique_facebook_task_assing_pair",
                    )
                ],
            },
        ),
    ]
