# Generated by Django 5.1.1 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0026_facebooktaskassing"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookprofile",
            name="page_access_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="facebookprofile",
            name="page_followers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="facebookprofile",
            name="page_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="facebookprofile",
            name="page_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="facebookprofile",
            name="page_url",
            field=models.URLField(blank=True),
        ),
    ]
