# Generated by Django 5.1.7 on 2026-05-04 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0032_video_source_profile_video_source_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
