# Generated by Django 5.1.7 on 2026-05-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0038_simplify_video_fields'),
    ]

    operations = []
