# Generated by Django 5.1.7 on 2026-05-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0041_merge_20260505_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberprofile',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('technology', 'Technology'), ('music', 'Music'), ('gaming', 'Gaming'), ('lifestyle', 'Lifestyle'), ('news', 'News'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
