# Generated by Django 5.1.7 on 2026-05-15 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0042_subscriberprofile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSubscribeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], db_index=True, default='pending', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_subscribe_tasks', to='subscribers.subscriberprofile')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_subscribe_targets', to='subscribers.subscriberprofile')),
            ],
            options={
                'db_table': 'manual_subscribe_table',
                'ordering': ['-updated_at', '-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'target_profile'), name='unique_manual_subscribe_task')],
            },
        ),
    ]
