# Generated by Django 5.1.7 on 2026-05-15 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0043_manualsubscribetask'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manualsubscribetask',
            table='manual_subscribe_task_table',
        ),
        migrations.CreateModel(
            name='ManualSubscribeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sub_score', models.PositiveIntegerField(default=0)),
                ('sub_reserve_score', models.PositiveIntegerField(default=0)),
                ('active_status_for_subscribe', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_subscribe_profile', to='subscribers.subscriberprofile')),
            ],
            options={
                'db_table': 'manual_subscribe_table',
                'ordering': ['-updated_at'],
            },
        ),
    ]
