# Generated by Django 5.1.7 on 2026-05-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0044_alter_manualsubscribetask_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manualsubscribeprofile',
            table='manual_subscribe_profile',
        ),
        migrations.AlterModelTable(
            name='manualsubscribetask',
            table='manual_subscribe_table',
        ),
    ]
