# Generated by Django 5.1.7 on 2026-05-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0045_alter_manualsubscribeprofile_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManualSubscribeTask',
        ),
    ]
