# Generated by Django 5.1.7 on 2026-05-15 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0046_delete_manualsubscribetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSubscribeTaskAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], db_index=True, default='unverified', max_length=16)),
                ('clicked_subscribe_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_subscribe_task_targets', to='subscribers.subscriberprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_subscribe_task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manual_subscribe_task_assign',
                'ordering': ['-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'target_profile'), name='unique_manual_subscribe_task_assign')],
            },
        ),
    ]
