# Generated by Django 5.1.7 on 2026-05-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0047_manualsubscribetaskassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualsubscribetaskassign',
            name='active_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='manualsubscribetaskassign',
            name='manual_subscribe_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments', to='subscribers.manualsubscribeprofile'),
        ),
    ]
