# Generated by Django 5.1.7 on 2026-05-17 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0053_manual_profile_isolation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
