# Generated by Django 5.1.7 on 2026-05-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0054_alter_subscriberprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualsubscribeprofile',
            name='profile',
        ),
    ]
